version: 2.1
orbs:
  # https://circleci.com/developer/orbs/orb/circleci/node
  node: circleci/node@4.1.0
  # https://circleci.com/developer/orbs/orb/circleci/aws-ecr
  aws-ecr: circleci/aws-ecr@6.15.0
  aws-eks: circleci/aws-eks@0.2.0
  kubernetes: circleci/kubernetes@1.3
jobs:
  test:
    executor:
      name: node/default
      tag: 14.15.1
    steps:
    - checkout
    - node/install-packages:
        pkg-manager: npm
    - run:
        command: npm test
        name: Run Mocha tests
    - store_artifacts:
        path: /tmp/test-results
        destination: raw-test-output
    - store_test_results:
        path: /tmp/test-results
  aws-cli-cred-setup:
    executor: aws-cli/default
    steps:
      - aws-cli/setup:
          aws-access-key-id: AWS_ACCESS_KEY
          aws-secret-access-key: AWS_ACCESS_SECRET
          aws-region: AWS_REGION_NAME
          aws-profile: AWS_PROFILE
  deploy-application:
    executor: aws-eks/python3
    parameters:
      cluster-name:
        description: |
          Name of the EKS cluster
        type: string
      docker-image-name:
        description: |
          Name of the docker image to be deployed
        type: string
      version-info:
        description: |
          App version information
        type: string
      aws-region:
        description: |
          AWS region
        type: string
        default: ""
      authenticator-release-tag:
        default: ''
        description: |
          Specifies which release-tag version of the authenticator to install.
        type: string
      aws-profile:
        default: ''
        description: |
          The AWS profile to be used. If not specified, the configured default
          profile for your AWS CLI installation will be used.
        type: string  
    steps:
      - checkout
      - run:
          name: Create deployment manifest
          command: |
            # Replace the placeholders in the manifest with the intended values.
            # This is to avoid hardcoding the image name in the manifest, to make this
            # demo project more portable.
            BUILD_DATE=$(date '+%Y%m%d%H%M%S')
            cat deployment/demo-app-deployment.yaml.template |\
               sed "s|DOCKER_IMAGE_NAME|<< parameters.docker-image-name >>|\
                g;s|BUILD_DATE_VALUE|$BUILD_DATE|g;s|VERSION_INFO_VALUE|\
                << parameters.version-info >>|g" > deployment/demo-app-deployment.yaml
      - aws-eks/update-kubeconfig-with-authenticator:
          cluster-name: << parameters.cluster-name >>
          authenticator-release-tag: << parameters.authenticator-release-tag >>
          install-kubectl: true
          aws-region: << parameters.aws-region >>
          aws-profile: << parameters.aws-profile >>
      - kubernetes/create-or-update-resource:
          resource-file-path: "deployment/demo-app-deployment.yaml"
          get-rollout-status: true
          resource-name: deployment/demoapp
      - kubernetes/create-or-update-resource:
          resource-file-path: "deployment/demo-app-service.yaml"
          
workflows:
  node-tests:
    jobs:
    - test
    # Envs: AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY, AWS_REGION, AWS_ECR_ACCOUNT_URL
    
    - aws-ecr/build-and-push-image:
        repo: test
        tag: "latest,v0.1.${CIRCLE_BUILD_NUM}"
        dockerfile: build/Dockerfile.prod
        path: .
        requires:
          - test
    - aws-cli-cred-setup:
         requires:
            - aws-ecr/build-and-push-image
      
    - deploy-application:
         cluster-name: eks
         aws-region: $AWS_DEFAULT_REGION
         authenticator-release-tag: v0.5.1
         aws-profile: $AWS_PROFILE
         docker-image-name: "${AWS_ECR_URL}/test:${CIRCLE_SHA1}"
         version-info: "${CIRCLE_SHA1}"
         requires:
            - aws-cli-cred-setup
